version: '3.4'
services:

  fpm:
    build: 'docker/php'
    working_dir: '/app'
    volumes:
      - '.:/app'
      - '~/.composer:/root/composer'
    env_file: ['.env']

  nginx:
    image: nginx:1-alpine
    ports: ['8080:80']
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
